url: ""
baseurl: ""
title: "人工智能系统实验室"
description: "System of Artificial Intelligence Laboratory (SAIL)"

lang: zh-CN
timezone: Asia/Shanghai

markdown: kramdown
highlighter: rouge

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "page"

plugins:
  - jekyll-paginate
  - jekyll-sitemap
