url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "人工智能系统实验室(SAIL)" # the name of your site, e.g. ACME Corp.
description: "System of Artificial Intelligence Laboratory"
