menu:
- {name: '人员', url: '/people'}
- {name: '学术成果', url: '/publications'}
- {name: '科研项目', url: '/projects'}

teacher:
- name: '胡鹏飞'
  title: '教授'
  department: '计算机科学与技术学院'
  institution: '山东大学'
  research:
    - '异构计算'
    - '具身智能安全'
    - '移动计算'
    - '无线感知'
  email: 'phu@sdu.edu.cn'
  image: 'https://perfecthu.github.io/index_files/photo.jpg'
  url: 'https://perfecthu.github.io'
  bio: ''

- name: '李峰'
  title: '教授'
  department: '计算机科学与技术学院'
  institution: '山东大学'
  research:
    - '计算机网络'
    - '边缘计算'
    - '物联网'
  email: 'fli@sdu.edu.cn'
  image: 'https://funglee.github.io/images/fli2.jpeg'
  url: 'https://funglee.github.io'
  bio: ''

- name: '吴思'
  title: '教授'
  department: '计算机科学与技术学院'
  institution: '山东大学'
  research:
    - '人工智能系统'
    - '分布式系统'
    - '存储系统'
    - '容错编码'
  email: 'siwu5938@gmail.com'
  image: 'https://kobesi.github.io/wusi.png'
  url: 'https://kobesi.github.io'
  bio: ''

- name: '于勇波'
  title: '助理教授'
  department: '人工智能学院'
  institution: '山东大学'
  research:
    - '人工智能系统'
    - '机器学习'
  email: 'yongbo.yu@sdu.edu.cn'
  image: 'https://aisearch.sdu.edu.cn/ai_service/filesystem/ope/thumbnail/51589e6f-4726-4bbd-9d72-ff6ee060b76b.png?width=500&height=500'
  url: 'https://faculty.sdu.edu.cn/yuyongbo/zh_CN/index.htm'
  bio: ''

student:
- name: '李超群'
  title: '2023级博士生'
  level: '博士生'
  research:
    - '边缘计算'
    - '任务调度'
  email: 'chaoqunli@mail.sdu.edu.cn'
  url: 'https://supergroupli.github.io/chaoqunli/'

- name: '刘晋尧'
  title: '2024级博士生'
  level: '博士生'
  research:
    - 'MLsys'
    - 'GPU通信'
  email: 'jacelau@mail.sdu.edu.cn'
  url: 'https://seclee.com'

- name: '李少伟'
  title: '2024级博士生'
  level: '博士生'
  research:
    - '网络配置'
    - '机器学习'
  email: 'lishaowei6208@mail.sdu.edu.cn'
  url: ''

- name: '于红靖'
  title: '2025级博士生'
  level: '博士生'
  research: []
  email: 'yuhj@mail.sdu.edu.cn'
  url: ''

- name: '贾丁毅'
  title: '2025级博士生'
  level: '博士生'
  research: []
  email: '202521596@mail.sdu.edu.cn'
  url: ''

- name: '张智森'
  title: '2026级博士生'
  level: '博士生'
  research: []
  email: ''
  url: ''

- name: '罗涛'
  title: '2026级博士生'
  level: '博士生'
  research: []
  email: ''
  url: ''

- name: '马浩原'
  title: '2024级硕士生'
  level: '硕士生'
  research: []
  email: ''
  url: ''

- name: '孙中远'
  title: '2024级硕士生'
  level: '硕士生'
  research: []
  email: ''
  image: '/assets/img/people/sunzy.jpg'
  url: ''

- name: '王旭'
  title: '2024级硕士生'
  level: '硕士生'
  research: []
  email: ''
  url: ''

- name: '陈鹏宇'
  title: '2024级硕士生'
  level: '硕士生'
  research: []
  email: ''
  url: ''

- name: '刘念友'
  title: '2024级硕士生'
  level: '硕士生'
  research: []
  email: ''
  url: ''

- name: '白帅'
  title: '2025级硕士生'
  level: '硕士生'
  research: []
  email: ''
  url: ''

- name: '王清恒'
  title: '2025级硕士生'
  level: '硕士生'
  research: []
  email: ''
  url: ''

- name: '杨树'
  title: '2025级硕士生'
  level: '硕士生'
  research: []
  email: ''
  url: ''

- name: '盛柄涵'
  title: '2025级硕士生'
  level: '硕士生'
  research: []
  email: ''
  url: ''

social: []
